server:
  servlet:
    context-path: /usuario-metas/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/Usuario-Metas
      auto-index-creation: true